name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  ko-build:
    name: ko build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
      - run: go version
      - uses: actions/checkout@v3
      - uses: ko-build/setup-ko@v0.6
      - run: go version
      - run: go env
      - run: ko version
      - run: ko build --platform=linux/amd64,linux/arm64